# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

def shared_pods
   pod 'Alamofire'
   pod 'SAMKeychain'
end

target 'SjekkUt' do
   shared_pods
   pod 'HockeySDK'
   pod 'NSURLRequest-cURL'
   pod 'DateTools'
   pod 'FontAwesome+iOS'
   pod 'OCMock'
   pod 'AlamofireImage'
   pod 'AlamofireNetworkActivityIndicator'
   pod 'AlamofireSwiftyJSON'
end

target 'SjekkUtTests' do
   shared_pods
end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-SjekkUt/Pods-SjekkUt-acknowledgements.plist', 'SjekkUT/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
