# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

def shared_pods
   pod 'Alamofire', '~> 3.4'
   pod 'SAMKeychain', '~> 1.5.0'
end

target 'SjekkUt' do
   shared_pods
   pod 'HockeySDK', '~> 4.0.1'
   pod 'NSURLRequest-cURL', '~> 0.0.1'
   pod 'DateTools', '~> 1.5.0'
   pod 'FontAwesome+iOS', '~> 0.1.4'
   pod 'OCMock', '~> 3.3'
   pod 'Alamofire', '~> 3.4'
   pod 'AlamofireImage', '~> 2.0'
   pod 'AlamofireNetworkActivityIndicator', '~> 1.0'
end

target 'SjekkUtTests' do
   shared_pods
end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-SjekkUt/Pods-SjekkUt-acknowledgements.plist', 'SjekkUT/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
